/*
 *
 * Copyright SHMsoft, Inc. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.freeeed.ui;

import org.freeeed.helpers.ProgressBar;
import org.freeeed.helpers.ProcessProgressUIHelper;
import org.freeeed.main.ActionProcessing;
import org.freeeed.services.Project;
import org.freeeed.services.Stats;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;

/**
 * @author ivanl
 */
public class ProcessProcessProgressUI extends javax.swing.JDialog implements ProcessProgressUIHelper {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProcessProcessProgressUI.class);
    private boolean processingFinished = false;
    private long total = 1;
    private final ActionProcessing processing;
    private Thread processingThread;

    /**
     * instance is used only when it exists. For Hadoop server-based processing
     * it will be null
     */
    private static ProcessProcessProgressUI instance;

    public synchronized ProcessProcessProgressUI getInstance() {
        return instance;
    }

    /**
     * Creates new form StagingProgressUI
     *
     * @param parent
     * @param modal
     */
    public ProcessProcessProgressUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInitComponents();
        processing = new ActionProcessing(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        fileLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Processing");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Staging"), "Processing progress"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                                        .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(fileLabel)
                                .addContainerGap())
        );

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(okButton)
                                        .addComponent(cancelButton))
                                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cancelProcessing();
    }//GEN-LAST:event_formWindowClosing

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        cancelProcessing();
    }//GEN-LAST:event_cancelButtonActionPerformed

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            Project.getCurrentProject().setStopThePresses(false);
            startProcessing();
            centerWindow(this);
            instance = this;
            ProgressBar.initialize(this);
        }

        super.setVisible(visible);
    }

    private void cancelProcessing() {
        if (processingFinished) {
            return;
        }
        EventQueue.invokeLater(() -> {
            int confirm = JOptionPane.showConfirmDialog(null, "Please confirm cancel processing");
            if (confirm == JOptionPane.OK_OPTION) {
                processing.setInterrupted(true);
                Project.getCurrentProject().setStopThePresses(true);
                try {
                    processingThread.join();
                } catch (InterruptedException e) {
                    e.printStackTrace(System.out);
                }
                doClose();
            }
        });

    }

    private void doClose() {
        setVisible(false);
        dispose();
    }

    private void myInitComponents() {
        okButton.setEnabled(false);
        progressBar.setValue(0);
        progressBar.setStringPainted(true);
    }

    public void setProcessingFinished() {
        this.processingFinished = true;
    }

    /**
     * Callback for progress update
     *
     * @param fileName - file being processed
     */
    @Override
    public void setProcessingState(final String fileName) {
        EventQueue.invokeLater(() -> {
            fileLabel.setText(fileName);
        });
    }

    /**
     * Callback for progress update
     */
    public synchronized void setDone() {
        EventQueue.invokeLater(() -> {
            progressBar.setValue(100);
            processingFinished = true;
            okButton.setEnabled(true);
        });

    }

    /**
     * Callback for progress update
     *
     * @param total
     */
    @Override
    public void setTotalSize(long total) {
        this.total = total;
    }

    public void resetCurrentSize() {
        EventQueue.invokeLater(() -> {
            progressBar.setValue(0);
        });
    }

    /**
     * Callback for progress update
     *
     * @param fileName
     */
    public void updateProcessingFile(final String fileName) {
        final String displayName = (fileName.length() <= 72)
                ? fileName
                : "..." + fileName.substring(fileName.length() - 72);
        EventQueue.invokeLater(() -> {
            fileLabel.setText(displayName);
        });
    }

    /**
     * Callback for progress update
     *
     * @param size of files copied so far
     */
    public void updateProgress(long size) {
        final long value = total == 0 ? 0 : size * 100 / total;
        LOGGER.trace("Processing progress: {} of the total {}", value, total);
        EventQueue.invokeLater(() -> {
            progressBar.setValue((int) value);
        });
    }

    /**
     * Callback for progress update
     */
    public void startProcessing() {
        String projectName = Project.getCurrentProject().getProjectName();
        Stats.getInstance().setJobStarted(projectName);
        processingThread = new Thread(processing);
        processingThread.start();
    }

    public static void centerWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
