/*
 *
 * Copyright SHMsoft, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.freeeed.ui;

import org.freeeed.db.DbLocalUtils;
import org.freeeed.main.ParameterProcessing;
import org.freeeed.services.Project;
import org.freeeed.services.Settings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;

/**
 * @author mark
 */
public class ProjectUI extends JDialog {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProjectUI.class);
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private JRadioButton blockChainRadioButton;
    private JTextField fromTextField;
    private JTextField toTextField;

    /**
     * Creates new form ProcessingParametersUI
     *
     * @param parent
     */
    public ProjectUI(Frame parent) {
        super(parent, true);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = rootPane.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = rootPane.getActionMap();
        actionMap.put(cancelName, new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        searchButtonGroup = new ButtonGroup();
        metadataButtonGroup = new ButtonGroup();
        dataSourceButtonGroup = new ButtonGroup();
        okButton = new JButton();
        tabPanel = new JTabbedPane();
        tabPanel.setPreferredSize(new Dimension(1000, 700));
        inputsPanel = new JPanel();
        projectCodeLabel = new JLabel();
        projectCodeField = new JTextField();
        projectNameLabel = new JLabel();
        projectNameField = new JTextField();
        projectInputsLabel = new JLabel();
        networkHelpLabel = new JLabel();
        addFileButton = new JButton();
        addNetworkButton = new JButton();
        removeButton = new JButton();
        projectInputsScrollPanel = new JScrollPane();
        projectInputsList = new JList();
        dataSourcePanel = new JPanel();
        dataSourceButton1 = new JRadioButton();
        dataSourceButton2 = new JRadioButton();
        dataSourceButton3 = new JRadioButton();
        loadFormatChoice = new JComboBox<>();
        stagingPanel = new JPanel();
        stagingZipSizeLabel = new JLabel();
        stagingZipSizeText = new JTextField();
        stageInPlaceCheck = new JCheckBox();
        explainButton = new JButton();
        metadataPanel = new JPanel();
        fieldSeparatorLabel = new JLabel();
        fieldSeparatorChoice = new JComboBox();
        labelMetadataCollected = new JLabel();
        standardMetadataRadio = new JRadioButton();
        allMetadataRadio = new JRadioButton();
        denistCheck = new JCheckBox();
        textInMetadataBox = new JCheckBox();
        ocrPanel = new JPanel();
        ocrCheck = new JCheckBox();
        cullingPanel = new JPanel();
        cullingLabel = new JLabel();
        helpLabel = new JLabel();
        cullingScrollPanel = new JScrollPane();
        cullingText = new JTextArea();
        imagingPanel = new JPanel();
        jPanel2 = new JPanel();
        createPdfImageCheckBox = new JCheckBox();
        jLabel2 = new JLabel();
        previewCheck = new JCheckBox();
        searchPanel = new JPanel();
        jPanel5 = new JPanel();
        luceneIndexEnabledRadioButton = new JRadioButton();
        esIndexEnabledRadioButton = new JRadioButton();
        noIndexCreationRadioButton = new JRadioButton();
        cancelButton = new JButton();
        Project currentProject = Project.getCurrentProject();
        fromBlock = new JSpinner(new SpinnerNumberModel(currentProject.getBlockFrom(), 0, Integer.MAX_VALUE, 1));
        toBlock = new JSpinner(new SpinnerNumberModel(currentProject.getBlockTo(), 0, Integer.MAX_VALUE, 1));
        ((JSpinner.DefaultEditor) fromBlock.getEditor()).getTextField().setColumns(6);
        ((JSpinner.DefaultEditor) toBlock.getEditor()).getTextField().setColumns(6);

        toBlock.addChangeListener(e -> {
            int value = (int) ((JSpinner) e.getSource()).getValue();
            currentProject.setBlockTo(value);
        });

        fromBlock.addChangeListener(e -> {
            int value = (int) ((JSpinner) e.getSource()).getValue();
            currentProject.setBlockFrom(value);
        });

        setTitle("Project Options");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new GridBagLayout());

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(9, 634, 16, 0);
        getContentPane().add(okButton, gridBagConstraints);
        getRootPane().setDefaultButton(okButton);

        //Input - start
        inputsPanel.setLayout(new GridBagLayout());

        projectCodeLabel.setText("Project code");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(19, 15, 0, 0);
        inputsPanel.add(projectCodeLabel, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(16, 27, 0, 0);
        inputsPanel.add(projectCodeField, gridBagConstraints);

        projectNameLabel.setText("Name");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(21, 15, 0, 0);
        inputsPanel.add(projectNameLabel, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 597;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 27, 0, 0);
        inputsPanel.add(projectNameField, gridBagConstraints);

        projectInputsLabel.setText("Add/Remove input data:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(22, 15, 0, 0);
        inputsPanel.add(projectInputsLabel, gridBagConstraints);

        networkHelpLabel.setForeground(new Color(0, 0, 255));
        networkHelpLabel.setText("Help");
        networkHelpLabel.setToolTipText("Click here for help on URI");
        networkHelpLabel.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                networkHelpLabelMouseEntered(evt);
            }

            public void mouseExited(MouseEvent evt) {
                networkHelpLabelMouseExited(evt);
            }

            public void mousePressed(MouseEvent evt) {
                networkHelpLabelMousePressed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(22, 6, 0, 0);
        inputsPanel.add(networkHelpLabel, gridBagConstraints);

        addFileButton.setText("Add local folder or file");
        addFileButton.addActionListener(this::addFileButtonActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 6, 0, 0);
        inputsPanel.add(addFileButton, gridBagConstraints);

        addNetworkButton.setText("Add network (URI) location");
        addNetworkButton.setToolTipText("<html>Add network location in the URI format. <br />\nExample of ftp access: <br />\nftp://user:password@ftp.example.com/path/file.zip\n</html>");
        addNetworkButton.addActionListener(this::addNetworkButtonActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 15, 0, 0);
        inputsPanel.add(addNetworkButton, gridBagConstraints);

        removeButton.setText("Remove");
        removeButton.setToolTipText("Remove local folder or network location from project inputs - \nthe data itself remains intact");
        removeButton.addActionListener(this::removeButtonActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 30, 0, 34);
        inputsPanel.add(removeButton, gridBagConstraints);

        projectInputsScrollPanel.setViewportView(projectInputsList);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 690;
        gridBagConstraints.ipady = 160;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(18, 15, 0, 0);
        inputsPanel.add(projectInputsScrollPanel, gridBagConstraints);

        dataSourcePanel.setBorder(BorderFactory.createTitledBorder("Data source"));
        dataSourcePanel.setLayout(new GridBagLayout());

        dataSourceButtonGroup.add(dataSourceButton1);
        dataSourceButton1.setText("eDiscovery");
        dataSourceButton1.setToolTipText("<html>\nInput comes from \n<ul>\n<li> mail boxes</li>\n<li>loose files</li>\n<li>and any of the 1,400 files recognized by FreeEed for eDiscovery</li>\n</ul>\n</html>");
        dataSourceButton1.addActionListener(this::dataSourceButton1ActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(22, 6, 17, 0);
        dataSourcePanel.add(dataSourceButton1, gridBagConstraints);

        dataSourceButtonGroup.add(dataSourceButton2);
        dataSourceButton2.setText("Load file");
        dataSourceButton2.setToolTipText("<html>\nInput comes from a CSV file<br/>\n<ul>\n<li>It can be the result of eDiscovery</li>\n<li>Or any other metadata file</li>\n<li>Fields should be the same as output by FreeEed</li>\n</ul>\n</html>");
        dataSourceButton2.addActionListener(this::dataSourceButton2ActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(22, 7, 17, 0);
        dataSourcePanel.add(dataSourceButton2, gridBagConstraints);

        loadFormatChoice.setModel(new DefaultComboBoxModel<>(new String[]{"CSV", "JSON"}));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(23, 18, 0, 21);
        dataSourcePanel.add(loadFormatChoice, gridBagConstraints);

        dataSourceButtonGroup.add(dataSourceButton3);
        dataSourceButton3.setText("Blockchain range : ");
        dataSourceButton3.addActionListener(this::dataSourceButton3ActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(22, 7, 17, 0);
        dataSourcePanel.add(dataSourceButton3, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(22, 7, 17, 0);
        dataSourcePanel.add(fromBlock, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(22, 7, 17, 0);
        dataSourcePanel.add(toBlock, gridBagConstraints);


        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 33;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(27, 15, 0, 0);
        inputsPanel.add(dataSourcePanel, gridBagConstraints);

        tabPanel.addTab("Inputs", inputsPanel);

        //Input - end

        stagingPanel.setLayout(new GridBagLayout());

        stagingZipSizeLabel.setText("Staging zip size, GB");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(36, 15, 0, 0);
        stagingPanel.add(stagingZipSizeLabel, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(33, 0, 0, 441);
        stagingPanel.add(stagingZipSizeText, gridBagConstraints);

        stageInPlaceCheck.setText("Read files directly");
        stageInPlaceCheck.setToolTipText("");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(71, 15, 262, 0);
        stagingPanel.add(stageInPlaceCheck, gridBagConstraints);

        explainButton.setText("Explain");
        explainButton.addActionListener(this::explainButtonActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(71, 5, 262, 0);
        stagingPanel.add(explainButton, gridBagConstraints);

        tabPanel.addTab("Staging", stagingPanel);

        metadataPanel.setLayout(new GridBagLayout());

        fieldSeparatorLabel.setText("Field separator");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(46, 28, 0, 0);
        metadataPanel.add(fieldSeparatorLabel, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(46, 13, 0, 0);
        metadataPanel.add(fieldSeparatorChoice, gridBagConstraints);

        labelMetadataCollected.setText("Metadata collected");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(29, 28, 0, 0);
        metadataPanel.add(labelMetadataCollected, gridBagConstraints);

        metadataButtonGroup.add(standardMetadataRadio);
        standardMetadataRadio.setSelected(true);
        standardMetadataRadio.setText("Standard");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(25, 36, 0, 0);
        metadataPanel.add(standardMetadataRadio, gridBagConstraints);

        metadataButtonGroup.add(allMetadataRadio);
        allMetadataRadio.setText("All");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(25, 7, 0, 473);
        metadataPanel.add(allMetadataRadio, gridBagConstraints);

        denistCheck.setSelected(true);
        denistCheck.setText("Remove system files");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(30, 28, 0, 0);
        metadataPanel.add(denistCheck, gridBagConstraints);

        textInMetadataBox.setText("Insert text in metadata");
        textInMetadataBox.setToolTipText("Useful for Concordance and Hive load");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 28, 189, 0);
        metadataPanel.add(textInMetadataBox, gridBagConstraints);

        tabPanel.addTab("Metadata", metadataPanel);

        ocrPanel.setLayout(new GridBagLayout());

        ocrCheck.setSelected(true);
        ocrCheck.setText("Perform OCR");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(31, 15, 361, 677);
        ocrPanel.add(ocrCheck, gridBagConstraints);

        tabPanel.addTab("OCR", ocrPanel);

        cullingPanel.setLayout(new GridBagLayout());

        cullingLabel.setText("Culling expressions");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(16, 15, 0, 0);
        cullingPanel.add(cullingLabel, gridBagConstraints);

        helpLabel.setForeground(new Color(0, 0, 255));
        helpLabel.setText("Help");
        helpLabel.setToolTipText("<html>Each line is treated as a separate keyword or search expression<br>\nAll lines are considered as connected by a non-exclusive \"OR\"<br>\nField names are required, so for example you can have<br><br>\ncontent:email<br>\ncontent:data<br>\ntitle:meeting<br><br>\nFor the syntax of search expressions click on this \"Help\"</html>");
        helpLabel.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                helpLabelMouseEntered(evt);
            }

            public void mouseExited(MouseEvent evt) {
                helpLabelMouseExited(evt);
            }

            public void mousePressed(MouseEvent evt) {
                helpLabelMousePressed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(16, 18, 0, 0);
        cullingPanel.add(helpLabel, gridBagConstraints);

        cullingText.setColumns(20);
        cullingText.setRows(5);
        cullingScrollPanel.setViewportView(cullingText);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 757;
        gridBagConstraints.ipady = 328;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new Insets(9, 15, 16, 15);
        cullingPanel.add(cullingScrollPanel, gridBagConstraints);

        tabPanel.addTab("Culling", cullingPanel);

        imagingPanel.setLayout(new GridBagLayout());

        jPanel2.setBorder(BorderFactory.createTitledBorder("Imaging Properties"));
        jPanel2.setLayout(new GridBagLayout());

        createPdfImageCheckBox.setText("Create PDF Images, multi-page, for every file");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 21, 68, 0);
        jPanel2.add(createPdfImageCheckBox, gridBagConstraints);

        jLabel2.setText("Control PDF image creation by changing the properties below");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(38, 21, 0, 243);
        jPanel2.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(19, 21, 0, 87);
        imagingPanel.add(jPanel2, gridBagConstraints);

        previewCheck.setText("Generate HTML documens for quick preview");
        previewCheck.setToolTipText("This option is for FreeEed Review. It generates HTML files for quick view");
        previewCheck.addActionListener(this::previewCheckActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(12, 33, 159, 0);
        imagingPanel.add(previewCheck, gridBagConstraints);

        tabPanel.addTab("Imaging", imagingPanel);

        searchPanel.setLayout(new GridBagLayout());

        jPanel5.setBorder(BorderFactory.createTitledBorder("Index options"));
        jPanel5.setLayout(new GridBagLayout());

        searchButtonGroup.add(luceneIndexEnabledRadioButton);
        luceneIndexEnabledRadioButton.setText("Create Lucene index (for geeks)");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(8, 17, 26, 379);
        jPanel5.add(luceneIndexEnabledRadioButton, gridBagConstraints);

        searchButtonGroup.add(esIndexEnabledRadioButton);
        esIndexEnabledRadioButton.setText("Prepare Elastic Search");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(1, 17, 0, 0);
        jPanel5.add(esIndexEnabledRadioButton, gridBagConstraints);

        searchButtonGroup.add(noIndexCreationRadioButton);
        noIndexCreationRadioButton.setSelected(true);
        noIndexCreationRadioButton.setText("No Search");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(38, 17, 0, 0);
        jPanel5.add(noIndexCreationRadioButton, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(24, 18, 208, 136);
        searchPanel.add(jPanel5, gridBagConstraints);

        tabPanel.addTab("Search", searchPanel);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -144;
        gridBagConstraints.ipady = -154;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        getContentPane().add(tabPanel, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(9, 18, 16, 0);
        getContentPane().add(cancelButton, gridBagConstraints);

        pack();
    }// </editor-fold>

    private void okButtonActionPerformed(ActionEvent evt) {
        try {
            if (saveData() == false) {
                return;
            }
            Project project = Project.getCurrentProject();
            DbLocalUtils.saveProject(project);
            FreeEedUI.getInstance().updateTitle(project.getProjectName());
        } catch (Exception e) {
            LOGGER.error("Error saving project", e);
            JOptionPane.showMessageDialog(this, "Error saving project");
        }
        doClose(RET_OK);
    }

    private void cancelButtonActionPerformed(ActionEvent evt) {
        doClose(RET_CANCEL);
    }

    /**
     * Closes the dialog
     */
    private void closeDialog(WindowEvent evt) {
        doClose(RET_CANCEL);
    }

    private void helpLabelMouseEntered(MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    private void helpLabelMouseExited(MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }

    private void helpLabelMousePressed(MouseEvent evt) {
        openLuceneSyntaxBrowser();
    }

    private void networkHelpLabelMouseEntered(MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    private void networkHelpLabelMouseExited(MouseEvent evt) {
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }

    private void networkHelpLabelMousePressed(MouseEvent evt) {
        openUriSyntaxBrowser();
    }

    private void addFileButtonActionPerformed(ActionEvent evt) {
        addFileInput();
    }

    private void addNetworkButtonActionPerformed(ActionEvent evt) {
        addUriInput();
    }

    private void removeButtonActionPerformed(ActionEvent evt) {
        removeInput();
    }

    private void explainButtonActionPerformed(ActionEvent evt) {
        JOptionPane.showMessageDialog(this,
                "Staging step is always required.\n"
                        + "However, this option will bypass preparing data in zip files.\n"
                        + "Instead, data will be read directly from the source directories or zip files.\n"
                        + "To keep in mind:\n"
                        + "Directories need to be accessible from every Mapper if running on the cluster\n"
                        + "This option may make staging faster but processing slower");
    }

    private void dataSourceButton1ActionPerformed(ActionEvent evt) {
        loadFormatChoice.setEnabled(false);
        Project.getCurrentProject().setDataSource(Project.DATA_SOURCE_EDISCOVERY);
    }

    private void dataSourceButton2ActionPerformed(ActionEvent evt) {
        loadFormatChoice.setEnabled(true);
        Project.getCurrentProject().setDataSource(Project.DATA_SOURCE_LOAD_FILE);
    }

    private void dataSourceButton3ActionPerformed(ActionEvent evt) {
        loadFormatChoice.setEnabled(false);
        Project.getCurrentProject().setDataSource(Project.DATA_SOURCE_BLOCKCHAIN);
    }

    private void previewCheckActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }


    // Variables declaration - do not modify
    private JButton addFileButton;
    private JButton addNetworkButton;
    private JRadioButton allMetadataRadio;
    private JButton cancelButton;
    private JCheckBox createPdfImageCheckBox;
    private JLabel cullingLabel;
    private JPanel cullingPanel;
    private JScrollPane cullingScrollPanel;
    private JTextArea cullingText;
    private JRadioButton dataSourceButton1;
    private JRadioButton dataSourceButton2;
    private JRadioButton dataSourceButton3;
    private ButtonGroup dataSourceButtonGroup;
    private JPanel dataSourcePanel;
    private JCheckBox denistCheck;
    private JButton explainButton;
    private JComboBox fieldSeparatorChoice;
    private JLabel fieldSeparatorLabel;
    private JLabel helpLabel;
    private JPanel imagingPanel;
    private JPanel inputsPanel;
    private JLabel jLabel2;
    private JPanel jPanel2;
    private JPanel jPanel5;
    private JLabel labelMetadataCollected;
    private javax.swing.JComboBox<String> loadFormatChoice;
    private JRadioButton luceneIndexEnabledRadioButton;
    private ButtonGroup metadataButtonGroup;
    private JPanel metadataPanel;
    private JLabel networkHelpLabel;
    private JRadioButton noIndexCreationRadioButton;
    private JCheckBox ocrCheck;
    private JPanel ocrPanel;
    private JButton okButton;
    private JCheckBox previewCheck;
    private JTextField projectCodeField;
    private JLabel projectCodeLabel;
    private JLabel projectInputsLabel;
    private JList projectInputsList;
    private JScrollPane projectInputsScrollPanel;
    private JTextField projectNameField;
    private JLabel projectNameLabel;
    private JButton removeButton;
    private ButtonGroup searchButtonGroup;
    private JPanel searchPanel;
    private JRadioButton esIndexEnabledRadioButton;
    private JCheckBox stageInPlaceCheck;
    private JPanel stagingPanel;
    private JLabel stagingZipSizeLabel;
    private JTextField stagingZipSizeText;
    private JRadioButton standardMetadataRadio;
    private JTabbedPane tabPanel;
    private JCheckBox textInMetadataBox;
    private JSpinner fromBlock;
    private JSpinner toBlock;
    // End of variables declaration
    private int returnStatus = RET_CANCEL;

    private void openLuceneSyntaxBrowser() {
        String url = "http://lucene.apache.org/core/old_versioned_docs/versions/3_5_0/queryparsersyntax.html";
        UtilUI.openBrowser(null, url);
    }

    private void openUriSyntaxBrowser() {
        String url = "http://en.wikipedia.org/wiki/URI_scheme#Generic_syntax";
        UtilUI.openBrowser(null, url);
    }

    private void showData() {
        showProjectInputs();
        showProcessingParametersData();
    }

    @SuppressWarnings("unchecked")
    private void showProjectInputs() {
        Project project = Project.getCurrentProject();
        setTitle("Settings for project " + project.getProjectName());
        projectCodeField.setText(project.getProjectCode());
        projectNameField.setText(project.getProjectName());

        DefaultListModel model = new DefaultListModel();
        String[] dirs = project.getInputs();
        String[] custodians = project.getCustodians(dirs);
        if (dirs != null) {
            for (int i = 0; i < dirs.length; ++i) {
                String custodian = i < custodians.length ? custodians[i] : "";
                String line = custodian + ": " + dirs[i];
                model.addElement(line.trim());
            }
        }
        int projectInputs = (dirs != null ? dirs.length : 0);
        projectInputsLabel.setText("Project inputs (" + projectInputs + ")");
        projectInputsList.setModel(model);
        cullingText.setText(project.getCullingAsTextBlock());
        String envSetting = Settings.getSettings().getEnv();
        project.setEnvironment(envSetting);
    }

    private boolean saveData() {
        boolean result = collectProjectInputs();
        if (result == false) {
            return false;
        }
        result = collectProcessingParametersData();
        return result != false;
    }

    private boolean collectProjectInputs() {
        Project project = Project.getCurrentProject();
        project.setProjectName(projectNameField.getText());
        ListModel model = projectInputsList.getModel();
        String[] dirs = new String[model.getSize()];
        String[] custodians = new String[model.getSize()];
        for (int i = 0; i < model.getSize(); ++i) {
            String line = (String) model.getElementAt(i);
            int twodots = line.indexOf(":");
            String custodian = line.substring(0, twodots);
            String uri = line.substring(twodots + 2);
            custodians[i] = custodian.trim();
            dirs[i] = uri.trim();
        }
        project.setInputs(dirs);
        project.setCustodians(custodians);
        project.setEnvironment("local");
        project.setCulling(cullingText.getText());
        return true;
    }

    private void removeInput() {
        int index = projectInputsList.getSelectedIndex();
        if (index >= 0) {
            ((DefaultListModel) projectInputsList.getModel()).remove(index);
        }
        projectInputsLabel.setText("Project inputs ("
                + projectInputsList.getModel().getSize() + ")");
    }

    @SuppressWarnings("unchecked")
    private void addFileInput() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        File f = null;
        Settings settings = Settings.getSettings();
        if (settings.getCurrentDir() != null) {
            f = new File(settings.getCurrentDir());
        } else {
            try {
                f = new File(new File(".").getCanonicalPath());
            } catch (IOException e) {
                e.printStackTrace(System.out);
            }
        }
        chooser.setCurrentDirectory(f);
        chooser.showOpenDialog(this);
        File file = chooser.getSelectedFile();
        if (file == null) {
            return;
        }
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, "File does not exist:\n" + file.getPath());
            return;
        }
        // Is this a directory with zip files only?
        boolean allZips = false;
        if (file.isDirectory()) {
            if (file.listFiles().length > 0) {
                allZips = true;
                for (File inside : file.listFiles()) {
                    if (!inside.isFile() || !inside.getName().toLowerCase().endsWith(".zip")) {
                        allZips = false;
                        break;
                    }
                }
            }
        }
        if (allZips) {
            int yesNo = JOptionPane.showConfirmDialog(this, "All files in this directory are zip file\n"
                    + "Package them separately as belonging to different custodians?\n"
                    + "(This will generate custodian names to be the same as file name)");
            if (yesNo != JOptionPane.YES_OPTION) {
                allZips = false;
            }
        }
        if (allZips) {
            File[] fileList = file.listFiles();
            Arrays.sort(fileList);
            for (File inside : fileList) {
                String custodian = "";
                String fileName = inside.getName();
                int lastUnderscore = fileName.lastIndexOf("_");
                if (lastUnderscore >= 0) {
                    custodian = fileName.substring(lastUnderscore + 1, fileName.length() - 4);
                }
                ((DefaultListModel) projectInputsList.getModel()).
                        addElement(custodian + ": " + inside.getPath());
            }
        } else {
            String custodian = "";
            if (dataSourceButton1.isSelected()) {
                custodian = JOptionPane.showInputDialog("Please enter custodian");
                if (custodian == null) {
                    return;
                }
            }
            ((DefaultListModel) projectInputsList.getModel()).addElement(custodian + ": " + file.getPath());
            projectInputsLabel.setText("Project inputs ("
                    + projectInputsList.getModel().getSize() + ")");
        }
        settings.setCurrentDir(file.getPath());
    }

    @SuppressWarnings("unchecked")
    private void addUriInput() {
        String uri = JOptionPane.showInputDialog(this, "Enter input's network locations as URI");
        if (uri == null) {
            return;
        }
        // TODO verify URI?
        String custodian = JOptionPane.showInputDialog("Please enter custodian");
        if (custodian == null) {
            return;
        }
        ((DefaultListModel) projectInputsList.getModel()).addElement(custodian + ": " + uri);
    }

    private void showProcessingParametersData() {
        Project project = Project.getCurrentProject();
        int index = 0;
        String fieldSeparator = project.getFieldSeparator();
        switch (fieldSeparator) {
            case "tab":
                index = 0;
                break;
            case "hex_one":
                index = 1;
                break;
            case "pipe":
                index = 2;
                break;
            case "carret":
                index = 3;
                break;
        }
        fieldSeparatorChoice.setSelectedIndex(index);
        allMetadataRadio.setSelected("all".equals(project.getMetadataCollect()));
        standardMetadataRadio.setSelected("standard".equals(project.getMetadataCollect()));
        denistCheck.setSelected(project.isRemoveSystemFiles());
        textInMetadataBox.setSelected(project.isTextInMetadata());
        stagingZipSizeText.setText(Double.toString(project.getGigsPerArchive()));
        ocrCheck.setSelected(project.isOcrEnabled());

        luceneIndexEnabledRadioButton.setSelected(project.isLuceneIndexEnabled());
        esIndexEnabledRadioButton.setSelected(project.isSendIndexToESEnabled());
        if (!project.isLuceneIndexEnabled() && !project.isSendIndexToESEnabled()) {
            noIndexCreationRadioButton.setSelected(true);
        }

        createPdfImageCheckBox.setSelected(project.isCreatePDF());
        previewCheck.setSelected(project.isPreview());
        dataSourceButton1.setSelected(project.getDataSource() == Project.DATA_SOURCE_EDISCOVERY);
        dataSourceButton2.setSelected(project.getDataSource() == Project.DATA_SOURCE_LOAD_FILE);
        dataSourceButton3.setSelected(project.getDataSource() == Project.DATA_SOURCE_BLOCKCHAIN);
        loadFormatChoice.setEnabled(dataSourceButton2.isSelected());
        stageInPlaceCheck.setSelected(project.isStageInPlace());
        loadFormatChoice.setSelectedItem(Project.getCurrentProject().getLoadFileFormat().toUpperCase());
    }

    private boolean collectProcessingParametersData() {
        Project project = Project.getCurrentProject();
        try {
            int index = fieldSeparatorChoice.getSelectedIndex();
            switch (index) {
                case 0:
                    project.setFieldSeparator("tab");
                    break;
                case 1:
                    project.setFieldSeparator("hex_one");
                    break;
                case 2:
                    project.setFieldSeparator("pipe");
                    break;
                case 3:
                    project.setFieldSeparator("carret");
                    break;
            }
            project.setMetadataCollect(standardMetadataRadio.isSelected() ? "standard" : "all");
            project.setRemoveSystemFiles(denistCheck.isSelected());
            project.setTextInMetadata(textInMetadataBox.isSelected());
            project.setGigsPerArchive(Double.parseDouble(stagingZipSizeText.getText()));
            project.setOcrEnabled(ocrCheck.isSelected());
            project.setLuceneIndexEnabled(luceneIndexEnabledRadioButton.isSelected());
            project.setSendIndexToESEnabled(esIndexEnabledRadioButton.isSelected());
            project.setCreatePDF(createPdfImageCheckBox.isSelected());
            project.setPreview(previewCheck.isSelected());
            project.setDataSource(getDataSourceSelected());
            project.setStageInPlace(stageInPlaceCheck.isSelected());
            project.setLoadFileFormat((String) loadFormatChoice.getSelectedItem());
            Object from = project.get(ParameterProcessing.FROM_BLOCK);
            if (from == null) {
                project.setBlockFrom(1);
            }
            Object to = project.get(ParameterProcessing.TO_BLOCK);
            if (to == null) {
                project.setBlockTo(10);
            }
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private int getDataSourceSelected() {
        if (dataSourceButton2.isSelected()) {
            return Project.DATA_SOURCE_LOAD_FILE;
        } else if (dataSourceButton3.isSelected()) {
            return Project.DATA_SOURCE_BLOCKCHAIN;
        }
        return Project.DATA_SOURCE_EDISCOVERY;
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            Project project = Project.getCurrentProject();
            if (project == null) {
                JOptionPane.showMessageDialog(rootPane, "Create or open a project first");
                return;
            }
            myInit();
            projectCodeField.setEnabled(false);
            showData();
        }
        super.setVisible(b);
    }

    private void myInit() {
        fieldSeparatorChoice.removeAllItems();
        fieldSeparatorChoice.addItem("tab (\\t)");
        fieldSeparatorChoice.addItem("non-ascii one (x0001)");
        fieldSeparatorChoice.addItem("pipe (|)");
        fieldSeparatorChoice.addItem("carret (^)");
    }
}
