/*
 *
 * Copyright SHMsoft, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.freeeed.ui;

import org.freeeed.main.FreeEedMain;
import org.freeeed.main.ParameterProcessing;
import org.freeeed.main.Version;
import org.freeeed.services.*;
import org.freeeed.util.FolderOpener;
import org.freeeed.util.LogFactory;
import org.freeeed.util.OsUtil;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.logging.Logger;

/**
 * @author mark
 */
public class FreeEedUI extends javax.swing.JFrame {

    private final static Logger LOGGER = LogFactory.getLogger(FreeEedUI.class.getName());
    public static String defaultTitle = ParameterProcessing.APP_NAME + ParameterProcessing.TM + " - e-Discovery, Search, and AI Platform";

    private static FreeEedUI instance;

    public static FreeEedUI getInstance() {
        return instance;
    }

    /**
     * Creates new form Main
     */
    public FreeEedUI() {
        LOGGER.info("Starting " + Version.getVersionAndBuild());
        LOGGER.info("System check:");
        if (OsUtil.isWindows()) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                     | UnsupportedLookAndFeelException e) {
                LOGGER.severe("UI ERROR " + e.getMessage());
            }
        }
        String systemCheckErrors = OsUtil.systemCheck();
        if (!systemCheckErrors.isEmpty()) {
            SystemCheckUI ui = new SystemCheckUI(this, true);
            ui.setSystemErrorsText(systemCheckErrors);
            ui.setVisible(true);
        }
        ArrayList<String> systemReport = SystemSummary.getSystemSummary();
        for (String stat : systemReport) {
            LOGGER.info(stat);
        }
        try {
            Mode.load();
            Settings.load();
        } catch (Exception e) {
            LOGGER.severe("Problem initializing internal db");
        }

        initComponents();
    }

    public void setInstance(FreeEedUI aInstance) {
        instance = aInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuItemProjects = new javax.swing.JMenuItem();
        menuItemHosting = new javax.swing.JMenuItem();
        menuItemBackup = new javax.swing.JMenuItem();
        menuItemSeparator = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuItemProjectOptions = new javax.swing.JMenuItem();
        processMenu = new javax.swing.JMenu();
        stageMenuItem = new javax.swing.JMenuItem();
        processMenuItem = new javax.swing.JMenuItem();
        processSeparator = new javax.swing.JPopupMenu.Separator();
        historyMenuItem = new javax.swing.JMenuItem();
        reviewMenu = new javax.swing.JMenu();
        menuItemOutputFolder = new javax.swing.JMenuItem();
        menuItemOpenSearchUI = new javax.swing.JMenuItem();
        menuItemOpenRawSolr = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        programSettingsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        manualMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FreeEed - Graphical User Interface");
        setResizable(false);
        setSize(new java.awt.Dimension(670, 500));

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        menuItemProjects.setText("Projects");
        menuItemProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProjectsActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemProjects);

        menuItemHosting.setText("Edition");
        menuItemHosting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHostingActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemHosting);

        menuItemBackup.setText("Backup/Restore");
        menuItemBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBackupActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemBackup);
        fileMenu.add(menuItemSeparator);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemExit);

        mainMenu.add(fileMenu);

        editMenu.setText("Edit");

        menuItemProjectOptions.setText("Project options");
        menuItemProjectOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProjectOptionsActionPerformed(evt);
            }
        });
        editMenu.add(menuItemProjectOptions);

        mainMenu.add(editMenu);

        processMenu.setText("Process");

        stageMenuItem.setText("Stage");
        stageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(stageMenuItem);

        processMenuItem.setText("Process");
        processMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(processMenuItem);
        processMenu.add(processSeparator);

        historyMenuItem.setText("System");
        historyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(historyMenuItem);

        mainMenu.add(processMenu);

        reviewMenu.setText("Review");

        menuItemOutputFolder.setText("See output files");
        menuItemOutputFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOutputFolderActionPerformed(evt);
            }
        });
        reviewMenu.add(menuItemOutputFolder);

        menuItemOpenSearchUI.setText("Go to review");
        menuItemOpenSearchUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenSearchUIActionPerformed(evt);
            }
        });
        reviewMenu.add(menuItemOpenSearchUI);

        menuItemOpenRawSolr.setText("Open SOLR index");
        menuItemOpenRawSolr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenRawSolrActionPerformed(evt);
            }
        });
        reviewMenu.add(menuItemOpenRawSolr);

        mainMenu.add(reviewMenu);

        settingsMenu.setText("Settings");

        programSettingsMenuItem.setText("Program settings");
        programSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programSettingsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(programSettingsMenuItem);

        mainMenu.add(settingsMenu);

        helpMenu.setText("Help");

        manualMenuItem.setText("Manual");
        manualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(manualMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new AboutDialog(this, true).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void changelogMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        UtilUI.openBrowser(FreeEedUI.getInstance(), "https://github.com/shmsoft/FreeEed/wiki/Changelog");
    }

    private void manualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        UtilUI.openBrowser(FreeEedUI.getInstance(), "https://github.com/shmsoft/FreeEed/wiki");
    }

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        try {
            exitApp();
        } catch (Exception e) {
            LOGGER.severe("Error saving project");
            JOptionPane.showMessageDialog(this, "Application error " + e.getMessage());
        }
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProjectsActionPerformed
        openProject();
    }//GEN-LAST:event_menuItemProjectsActionPerformed

    private void stageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageMenuItemActionPerformed
        stageProject();
    }//GEN-LAST:event_stageMenuItemActionPerformed

    private void processMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processMenuItemActionPerformed
        processProject();
    }//GEN-LAST:event_processMenuItemActionPerformed

    private void historyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyMenuItemActionPerformed
        showHistory();
    }//GEN-LAST:event_historyMenuItemActionPerformed

    private void menuItemProjectOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProjectOptionsActionPerformed
        showProcessingOptions();
    }//GEN-LAST:event_menuItemProjectOptionsActionPerformed

    private void programSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programSettingsMenuItemActionPerformed
        openProgramSettings();
    }//GEN-LAST:event_programSettingsMenuItemActionPerformed

    private void menuItemOpenRawSolrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenRawSolrActionPerformed
        openSolr();
    }//GEN-LAST:event_menuItemOpenRawSolrActionPerformed

    private void menuItemOpenSearchUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenSearchUIActionPerformed
        openReviewUI();
    }//GEN-LAST:event_menuItemOpenSearchUIActionPerformed

    private void menuItemOutputFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOutputFolderActionPerformed
        try {
            openOutputFolder();
        } catch (IOException e) {
            LOGGER.severe("Could not open folder");
            JOptionPane.showMessageDialog(this, "Something is wrong with the OS, please open the output folder manually");
        }
    }//GEN-LAST:event_menuItemOutputFolderActionPerformed

    private void menuItemBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBackupActionPerformed
        openBackupUtility();
    }//GEN-LAST:event_menuItemBackupActionPerformed

    private void menuItemHostingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHostingActionPerformed
        openHostingDialog();
    }//GEN-LAST:event_menuItemHostingActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        openBackupUtility();
    }//GEN-LAST:event_fileMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // the first argument is the app type
        // it can be M for med, or E for no argument
        String appType = args.length > 0 ? args[0] : "E";
        ParameterProcessing.setAppType(appType);

        java.awt.EventQueue.invokeLater(() -> {
            if (!shouldProceedAfterEditionDialog()) {
                return; // user cancelled
            }
            FreeEedUI ui = new FreeEedUI();
            ui.setInstance(ui);
            ui.setVisible(true);
        });
    }

    /**
     * @return true if app should continue to main UI, false if user cancelled.
     */
    private static boolean shouldProceedAfterEditionDialog() {
        try {
            // Startup occurs before FreeEedUI() constructor, so Settings.load() hasn't run yet.
            // Load DB-backed settings here, otherwise edition_remember is not available.
            try {
                Mode.load();
            } catch (Exception ignored) {
                // best-effort; Settings may still load
            }
            try {
                Settings.load();
            } catch (Exception ignored) {
                // best-effort; we'll fall back to defaults
            }

            Settings settings = Settings.getSettings();

            // If user asked to remember choice, skip dialog.
            if (settings.isEditionRemembered()) {
                return true;
            }

            // Modal dialog; blocks until closed.
            FreeEedEdition dialog = new FreeEedEdition(null, true);
            dialog.setVisible(true);

            if (dialog.isCancelled()) {
                return false;
            }

            // Persist selection when user clicks Continue.
            // If 'Remember' is checked, we save both remember flag and selection.
            // If not checked, we clear the remember flag (and stored selection) so dialog shows next launch.
            if (dialog.isRememberChoice()) {
                settings.setEditionRemembered(true);
                settings.setEditionSelected(dialog.getSelectedEdition());
            } else {
                settings.setEditionRemembered(false);
                settings.setEditionSelected("");
            }
            settings.save();

            return true;
        } catch (Exception e) {
            // If anything goes wrong, fail open (let user into app)
            LOGGER.warning("Could not process edition dialog settings: " + e.getMessage());
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem historyMenuItem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem manualMenuItem;
    private javax.swing.JMenuItem menuItemBackup;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHosting;
    private javax.swing.JMenuItem menuItemOpenRawSolr;
    private javax.swing.JMenuItem menuItemOpenSearchUI;
    private javax.swing.JMenuItem menuItemOutputFolder;
    private javax.swing.JMenuItem menuItemProjectOptions;
    private javax.swing.JMenuItem menuItemProjects;
    private javax.swing.JPopupMenu.Separator menuItemSeparator;
    private java.awt.Panel panel1;
    private javax.swing.JMenu processMenu;
    private javax.swing.JMenuItem processMenuItem;
    private javax.swing.JPopupMenu.Separator processSeparator;
    private javax.swing.JMenuItem programSettingsMenuItem;
    private javax.swing.JMenu reviewMenu;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenuItem stageMenuItem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setVisible(boolean b) {
        if (b) {
            myInitComponents();
            applyEditionFeatureGates();
        }
        super.setVisible(b);
    }

    /**
     * Hide/disable premium features based on remembered or current edition selection.
     */

    private void myInitComponents() {
        addWindowListener(new FrameListener());
        setBounds(64, 40, 640, 400);
        setLocationRelativeTo(null);
        String title = defaultTitle;
        setTitle(title);
    }

    private void exitApp() throws Exception {
        if (!isExitAllowed()) {
            return;
        }
        Settings.getSettings().save();
        setVisible(false);
        System.exit(0);
    }

    private boolean isExitAllowed() {
        return true;
    }

    private void openProject() {
        ProjectsUI dialog = new ProjectsUI(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    public void openProject(File selectedFile) {
        Project project = Project.loadFromFile(selectedFile);
        project.setProjectFilePath(selectedFile.getPath());
        updateTitle(project.getProjectCode() + " " + project.getProjectName());
        LOGGER.finest("Opened project file: " + selectedFile.getPath());
        Settings settings = Settings.getSettings();
        settings.addRecentProject(selectedFile.getPath());
        showProcessingOptions();
    }

    private class ProjectFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File file) {
            String filename = file.getName();
            return filename.endsWith(".project") || file.isDirectory();
        }

        @Override
        public String getDescription() {
            return "Project files";
        }
    }

    public void updateTitle(String title) {
        if (title != null) {
            setTitle(ParameterProcessing.APP_NAME + ParameterProcessing.TM + " - " + title);
        } else {
            setTitle(ParameterProcessing.APP_NAME + ParameterProcessing.TM);
        }
    }

    public void showProcessingOptions() {
        if (Project.getCurrentProject().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create or open a project first");
            return;
        }
        ProjectUI dialog = new ProjectUI(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void stageProject() {
        Project project = Project.getCurrentProject();
        if (project.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create or open a project first");
            return;
        }
        // check for empty input directories
        String[] dirs = project.getInputs();
        if (dirs.length == 0) {
            JOptionPane.showMessageDialog(rootPane, "You selected no data to stage");
            return;
        }
        for (String dir : dirs) {
            File file = new File(dir);
            if (file.isDirectory() && file.list().length == 0) {
                JOptionPane.showMessageDialog(rootPane, "Some of the directories you are trying to stage are empty. "
                        + "\\It does not make sense to stage them and may lead to confusion."
                        + "\\Please check the project directories");
                return;
            }
        }
        try {
            FreeEedMain.getInstance().runStagePackageInput();
        } catch (Exception e) {
            LOGGER.severe("Error staging project");
        }
    }

    private void runProcessing() throws IllegalStateException {
        Project project = Project.getCurrentProject();
        if (project.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create or open a project first");
            return;
        }
        project.setEnvironment(Project.ENV_LOCAL);
        FreeEedMain mainInstance = FreeEedMain.getInstance();
        if (new File(project.getResultsDir()).exists()) {
            // in most cases, it won't already exist, but just in case
            try {
                Util.deleteDirectory(new File(project.getResultsDir()));
            } catch (Exception e) {
                throw new IllegalStateException(e.getMessage());
            }
        }
        String processWhere = project.getProcessWhere();
        if (processWhere != null) {
            mainInstance.runProcessing(processWhere);
        } else {
            throw new IllegalStateException("No processing option selected.");
        }
    }

    private void showHistory() {
        SystemUI ui = new SystemUI();
        ui.setVisible(true);
    }

    private boolean areResultsPresent() {
        try {
            Project project = Project.getCurrentProject();
            if (project == null || project.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please open a project first");
                return false;
            }
            boolean success = Review.deliverFiles();
            if (!success) {
                JOptionPane.showMessageDialog(this, "No results yet");
                return false;
            }
        } catch (IOException e) {
            LOGGER.warning("Results present? Problem!");
            return false;
        }
        return true;
    }

    private void openOutputFolder() throws IOException {
        if (!areResultsPresent()) {
            return;
        }
        String resultsFolder = Project.getCurrentProject().getResultsDir();
        new FolderOpener(resultsFolder).execute();
    }

    class FrameListener extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent e) {
            try {
                Settings.getSettings().save();
            } catch (Exception ex) {
                LOGGER.severe("Error saving project");
                JOptionPane.showMessageDialog(null, "Application error " + ex.getMessage());
            }

        }
    }

    private void openWiki() {
        Settings settings = Settings.getSettings();
        String url = settings.getManualPage();
        UtilUI.openBrowser(this, url);
    }

    private void openProgramSettings() {
        ProgramSettingsUI programSettingsUI = new ProgramSettingsUI(this, true);
        programSettingsUI.setVisible(true);
    }

    private void openSolr() {
        Settings settings = Settings.getSettings();
        String url = settings.getSolrEndpoint() + "/solr/admin";
        UtilUI.openBrowser(this, url);
    }

    private void openReviewUI() {
        Settings settings = Settings.getSettings();
        String url = settings.getReviewEndpoint();
        UtilUI.openBrowser(this, url);
    }

    public void processProject() {
        try {
            runProcessing();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(this, "There were some problems with processing, \""
                    + e.getMessage() + "\n"
                    + "please check console output");
        }
    }

    private void openModeUI() {
        RunModeUI ui = new RunModeUI(this, true);
        ui.setVisible(true);
    }

    private void openWordCloudUI() {
        Project project = Project.getCurrentProject();
        if (project.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please open a project first");
            return;
        }
    }

    private void startSolr() {
        String command = "cd freeeed-solr/example; java -Xmx1024M -jar start.jar &";
        try {
            OsUtil.runCommand(command);
        } catch (IOException e) {
            LOGGER.severe("Problem starting SOLR");
        }
    }

    private void openBackupUtility() {
        if (OsUtil.isLinux()) {
            openBrowserToBackup();
        }
        String premiumFeatures = Settings.getSettings().getPremiumFeaturesDirectory();
        java.nio.file.Path backupUtilityPath = java.nio.file.Paths.get(
                        (premiumFeatures == null || premiumFeatures.trim().isEmpty()) ? "" : premiumFeatures.trim()
                ).resolve("releases")
                .resolve(OsUtil.whichOs());

        String backupUtility = backupUtilityPath.toString();

        LOGGER.info("Backup utility path: " + backupUtility + "/BackupRestore");
        //prepareBackupSettings(backupUtility);
        if (backupUtility == null || backupUtility.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Backup utility path is not configured");
            return;
        }

        File targetDir = new File(backupUtility);
        if (!targetDir.exists() || !targetDir.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Backup utility directory not found: " + targetDir.getPath());
            return;
        }
        // Choose executable name per OS
        String launcherName = OsUtil.isWindows() ? "BackupRestore.exe" : "BackupRestore";

        // OS-safe join
        java.nio.file.Path scriptPath = targetDir.toPath().resolve(launcherName);
        String script = scriptPath.toString();
        String cmd = script;
        try {
            OsUtil.runCommandDetached(cmd);
            LOGGER.info("Started BackupRestore utility:");
        } catch (IOException e) {
            LOGGER.severe("Problem starting BackupRestore utility: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                    "Could not start BackupRestore utility: " + e.getMessage());
        }
    }

    private void openBrowserToBackup() {
        try {
            URI uri = new URI("http://localhost:9000");

            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(uri);
                    return;
                }
            }

            // Linux fallback
            OsUtil.runCommandDetached("xdg-open " + uri);

        } catch (Exception e) {
            LOGGER.warning("Could not open browser automatically: " + e.getMessage());
        }
    }

    // helper to minimally escape backslashes and quotes for JSON strings
    private static String escapeForJson(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private void openHostingDialog() {
        FreeEedEdition ui = new FreeEedEdition(this, true);
        ui.setVisible(true);
        // refresh gates in case edition changed
        applyEditionFeatureGates();
    }

    private void applyEditionFeatureGates() {
        boolean isOpenSource = Settings.getSettings().isOpenSourceEdition();
        menuItemBackup.setEnabled(!isOpenSource);
    }
}
