/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/OkCancelDialog.java to edit this template
 */
package org.freeeed.ui;

import org.freeeed.services.Settings;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author mark
 */
public class FreeEedEdition extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FreeEedEdition.class.getName());
    private final Frame parent;
    
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form FreeEedEnvironment
     */
    public FreeEedEdition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        openSource = new javax.swing.JRadioButton();
        additionalFeatures = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cancelButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rememberEditionBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();

        setTitle("FreeEed Edition");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("Continue");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        buttonGroup1.add(openSource);
        openSource.setText("Open Source Edition (Free)");
        openSource.setToolTipText("");
        openSource.addActionListener(this::openSourceActionPerformed);

        buttonGroup1.add(additionalFeatures);
        additionalFeatures.setText("Additional Features (Paid)");
        additionalFeatures.setToolTipText("");
        additionalFeatures.addActionListener(this::additionalFeaturesActionPerformed);

        jLabel2.setText("Welcome to FreeEed");

        cancelButton1.setText("Learn more...");
        cancelButton1.addActionListener(this::cancelButton1ActionPerformed);

        jLabel3.setText("Select how you'd like to run FreeEed today. You can switch later in Settings.");

        jLabel4.setForeground(new java.awt.Color(96, 96, 96));
        jLabel4.setText("Core e-discovery workflow and standard features");

        jLabel5.setForeground(new java.awt.Color(96, 96, 96));
        jLabel5.setText("Unlock premium capabilties (e.g. Backup/Restore, AI)");

        jLabel6.setForeground(new java.awt.Color(120, 120, 120));
        jLabel6.setText("Paid features require an active license. You can switch later");

        rememberEditionBox.setForeground(new java.awt.Color(96, 96, 96));
        rememberEditionBox.setText("Remember my choice (don’t show this again)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(rememberEditionBox)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(openSource)
                                    .addComponent(additionalFeatures)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(cancelButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(openSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(additionalFeatures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(rememberEditionBox)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okButton)
                            .addComponent(cancelButton)
                            .addComponent(cancelButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        saveData();
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void openSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openSourceActionPerformed
        onProjectModeChanged();
    }//GEN-LAST:event_openSourceActionPerformed

    private void additionalFeaturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionalFeaturesActionPerformed
        onProjectModeChanged();
    }//GEN-LAST:event_additionalFeaturesActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        // Keep the dialog open; just launch help page in the browser.
        UtilUI.openBrowser(this, "https://github.com/shmsoft/FreeEed/wiki");

        // The browser often steals focus; bring this modal dialog back so the user can Continue/Cancel.
        // Some Linux window managers ignore toFront(), so we do a brief always-on-top toggle as a fallback.
        // Add a small delay so the OS/WM has time to raise the browser first; then we re-raise the dialog.
        try {
            final boolean wasAlwaysOnTop = isAlwaysOnTop();
            javax.swing.Timer t = new javax.swing.Timer(250, e -> {
                try {
                    setAlwaysOnTop(true);
                    toFront();
                    requestFocus();
                    requestFocusInWindow();
                } finally {
                    try {
                        setAlwaysOnTop(wasAlwaysOnTop);
                    } catch (Exception ignored2) {
                        // best-effort only
                    }
                }
            });
            t.setRepeats(false);
            t.start();
        } catch (Exception ignored) {
            // best-effort only
        }
    }//GEN-LAST:event_cancelButton1ActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FreeEedEdition dialog = new FreeEedEdition(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton additionalFeatures;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton openSource;
    private javax.swing.JCheckBox rememberEditionBox;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
    
        @Override
    public void setVisible(boolean b) {
        if (b) {
            setLocationRelativeTo(parent);
            showData();
        }
        onProjectModeChanged();
        super.setVisible(b);
    }
    private void onProjectModeChanged() {
        boolean credentialsRequired = !openSource.isSelected();
    }
    private void showData() {
        Settings settings = Settings.getSettings();
        boolean remembered = settings.isEditionRemembered();
        rememberEditionBox.setSelected(remembered);
        if (settings.getEditionSelected().isEmpty() || settings.getEditionSelected().equals("open_source")) {
            openSource.setSelected(true);
            additionalFeatures.setSelected(false);
        }
        if (settings.getEditionSelected().equals("additional_features")) {
            openSource.setSelected(false);
            additionalFeatures.setSelected(true);
        }

    }

    public static final String EDITION_OPEN_SOURCE = "open_source";
    public static final String EDITION_ADDITIONAL_FEATURES = "additional_features";

    /** True if user checked 'Remember my choice'. */
    public boolean isRememberChoice() {
        return rememberEditionBox != null && rememberEditionBox.isSelected();
    }

    /** Returns selected edition key. */
    public String getSelectedEdition() {
        return (additionalFeatures != null && additionalFeatures.isSelected())
                ? EDITION_ADDITIONAL_FEATURES
                : EDITION_OPEN_SOURCE;
    }

    /** Convenience: true when user closed with Cancel/Esc/X. */
    public boolean isCancelled() {
        return getReturnStatus() == RET_CANCEL;
    }
    private void saveData() {
        try {
            Settings settings = Settings.getSettings();

            // Save "remember" either way (so unchecking is persisted too).
            settings.setEditionRemembered(isRememberChoice());

            // Save selected edition only if user asked to remember it.
            if (isRememberChoice()) {
                settings.setEditionSelected(getSelectedEdition());
            }
            if (openSource.isSelected()) {
                settings.setEditionSelected(EDITION_OPEN_SOURCE);
            }
            if (additionalFeatures.isSelected()) {
                settings.setEditionSelected(EDITION_ADDITIONAL_FEATURES);
            }
            settings.save();
        } catch (Exception e) {
            logger.warning("Could not persist edition choice: " + e.getMessage());
        }
    }
}
